# Generated by Django 4.1.3 on 2022-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='om',
            name='foto',
            field=models.ImageField(upload_to='logo_om'),
        ),
    ]
