# Generated by Django 4.1.3 on 2022-11-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Om',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('PMPV', 'PMPV'), ('PMRJ', 'PMRJ'), ('PMN', 'PMN'), ('IBEX', 'IBEX'), ('HCE', 'HCE'), ('OCEX', 'OCEX')], max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
