# Generated by Django 4.1.3 on 2022-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='om',
            old_name='thumb',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='om',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='om',
            name='telefone',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
