# Generated by Django 4.1.3 on 2022-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_rename_thumb_om_foto_om_email_om_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='om',
            name='descricao',
        ),
    ]
