# Generated by Django 4.1.3 on 2022-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_om_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='om',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
