# Generated by Django 4.1.3 on 2022-11-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_om_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('nd', models.IntegerField(choices=[('30', '30'), ('39', '39'), ('52', '52')])),
                ('ug', models.IntegerField(choices=[('160242', '160242'), ('167242', '167242')])),
                ('pregao', models.CharField(default=0, max_length=8)),
                ('fornecedor', models.CharField(choices=[('BIOMEDICAL', 'BIOMEDICAL'), ('SULAR', 'SULAR'), ('MEDSANTA', 'MEDSANTA')], max_length=50)),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.om')),
            ],
        ),
    ]
