# Generated by Django 4.1.3 on 2022-11-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_empenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='data',
            field=models.DateField(),
        ),
    ]
