# Generated by Django 4.1.3 on 2022-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_empenho_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='pregao',
            field=models.CharField(max_length=8),
        ),
    ]
