# Generated by Django 4.1.3 on 2022-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_empenho_pregao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='nd',
            field=models.IntegerField(choices=[('30', 30), ('39', 30), ('52', 30)]),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='ug',
            field=models.IntegerField(choices=[('160242', 160242), ('167242', 167242)]),
        ),
    ]
