# Generated by Django 4.1.3 on 2022-11-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_alter_om_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='om',
            name='ch_almox',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='om',
            name='tel_ch_almox',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
