# Generated by Django 4.1.3 on 2022-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_om_ch_almox_om_tel_ch_almox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='om',
            name='tel_ch_almox',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
