# Generated by Django 4.1.3 on 2022-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_alter_om_tel_ch_almox'),
    ]

    operations = [
        migrations.AddField(
            model_name='om',
            name='adj_almox',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='om',
            name='tel_adj_almox',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
