# Generated by Django 4.1.3 on 2022-11-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_om_adj_almox_om_tel_adj_almox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='empenho',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.fornecedor'),
        ),
    ]
