# Generated by Django 4.1.3 on 2022-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_fornecedor_alter_empenho_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='nd',
            field=models.CharField(choices=[('30', '30'), ('39', '39'), ('52', '52')], max_length=2),
        ),
    ]
