# Generated by Django 4.1.3 on 2022-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0023_alter_empenho_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('ano', models.CharField(max_length=4)),
                ('situacao', models.CharField(choices=[('SITUACAO1', 'SITUACAO1'), ('SITUACAO2', 'SITUACAO2'), ('SITUACAO3', 'SITUACAO3')], max_length=20)),
            ],
        ),
    ]
