# Generated by Django 4.1.3 on 2022-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0024_pregao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregao',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='pregao',
            name='numero',
        ),
        migrations.AddField(
            model_name='pregao',
            name='numero_ano',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
