# Generated by Django 4.1.3 on 2022-11-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0025_remove_pregao_ano_remove_pregao_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='descrição',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregao',
            name='termo_homolocao',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregao',
            name='situacao',
            field=models.CharField(choices=[('HOMOLOGADO', 'HOMOLOGADO'), ('CJU', 'CJU')], max_length=20),
        ),
    ]
