# Generated by Django 4.1.3 on 2022-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0026_pregao_descrição_pregao_termo_homolocao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='oms_favorecidas',
            field=models.ManyToManyField(to='plataforma.om'),
        ),
    ]
