# Generated by Django 4.1.3 on 2022-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0027_pregao_oms_favorecidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='catalago',
            field=models.FileField(blank=True, null=True, upload_to='catalago'),
        ),
    ]
