# Generated by Django 4.1.3 on 2022-11-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0028_pregao_catalago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenho',
            name='nd',
        ),
        migrations.RemoveField(
            model_name='empenho',
            name='ug',
        ),
        migrations.AlterField(
            model_name='empenho',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.pregao'),
        ),
    ]
