# Generated by Django 4.1.3 on 2022-11-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0029_remove_empenho_nd_remove_empenho_ug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('fonte', models.CharField(max_length=10)),
                ('nd', models.CharField(max_length=6)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.planointerno')),
            ],
        ),
    ]
