# Generated by Django 4.1.3 on 2022-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0030_planointerno_notacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
