# Generated by Django 4.1.3 on 2022-11-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0031_empenho_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='nota_credito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.notacredito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empenho',
            name='plano_interno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.planointerno'),
            preserve_default=False,
        ),
    ]
