# Generated by Django 4.1.3 on 2022-11-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0033_alter_empenho_plano_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo1', models.FileField(upload_to='arquivo1-oms')),
                ('arquivo2', models.FileField(upload_to='arquivo2-oms')),
                ('arquivo3', models.FileField(upload_to='arquivo3-oms')),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.om')),
            ],
        ),
    ]
