# Generated by Django 4.1.3 on 2022-11-20 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0034_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
    ]
