# Generated by Django 4.1.3 on 2022-11-20 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0036_remove_arquivo_arquivo1_remove_arquivo_arquivo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
    ]
