# Generated by Django 4.1.3 on 2022-11-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0038_rename_numero_ano_pregao_pregao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.planointerno'),
        ),
    ]
