# Generated by Django 4.1.3 on 2022-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0039_alter_notacredito_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.planointerno'),
        ),
    ]
