# Generated by Django 4.1.3 on 2022-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0040_alter_notacredito_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='capacidade_empenho',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
