# Generated by Django 4.1.3 on 2022-11-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0041_pregao_capacidade_empenho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregao',
            old_name='capacidade_empenho',
            new_name='saldo_homologado',
        ),
    ]
