# Generated by Django 4.1.3 on 2022-11-21 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0042_rename_capacidade_empenho_pregao_saldo_homologado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 11, 21)),
        ),
    ]
