# Generated by Django 4.1.3 on 2022-11-22 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0043_alter_arquivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 11, 22)),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.fornecedor'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='nota_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.notacredito'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='plano_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.planointerno'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='pregao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.pregao'),
        ),
    ]
