# Generated by Django 4.1.3 on 2022-11-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0044_alter_arquivo_data_alter_empenho_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='om',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.om'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
