# Generated by Django 4.1.3 on 2022-11-24 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0045_alter_arquivo_om_alter_empenho_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
    ]
