# Generated by Django 4.1.3 on 2022-11-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0046_alter_arquivo_data'),
        ('plataforma', '0046_empenho_entregue_alter_arquivo_data'),
    ]

    operations = [
    ]
