# Generated by Django 4.1.3 on 2022-12-13 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0048_alter_arquivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 12, 41, 20, 431584, tzinfo=datetime.timezone.utc)),
        ),
    ]
