# Generated by Django 4.1.3 on 2022-12-13 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0049_alter_arquivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
