# Generated by Django 4.1.3 on 2022-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0050_alter_arquivo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='om',
        ),
        migrations.RemoveField(
            model_name='empenho',
            name='om',
        ),
        migrations.RemoveField(
            model_name='pregao',
            name='oms_favorecidas',
        ),
        migrations.DeleteModel(
            name='Om',
        ),
    ]
