# Generated by Django 4.1.3 on 2022-12-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
        ('plataforma', '0051_remove_arquivo_om_remove_empenho_om_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='om',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oms.om'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empenho',
            name='om',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oms.om'),
            preserve_default=False,
        ),
    ]
