# Generated by Django 4.1.3 on 2022-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
        ('plataforma', '0052_arquivo_om_empenho_om'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='oms_favorecidas',
            field=models.ManyToManyField(to='oms.om'),
        ),
        migrations.DeleteModel(
            name='Empenho',
        ),
    ]
