# Generated by Django 4.1.3 on 2022-12-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0053_pregao_oms_favorecidas_delete_empenho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregao',
            name='oms_favorecidas',
        ),
    ]
