# Generated by Django 4.1.3 on 2022-12-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0052_arquivo_om_empenho_om'),
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero', models.CharField(max_length=4)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('entregue', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.fornecedor')),
                ('nota_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.notacredito')),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.om')),
                ('plano_interno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.planointerno')),
                ('pregao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.pregao')),
            ],
        ),
    ]
