# Generated by Django 4.1.3 on 2022-12-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregoes', '0001_initial'),
        ('empenhos', '0002_alter_empenho_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='pregao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pregoes.pregao'),
        ),
    ]
